services:
  mariadb:
    image: mariadb:10.9
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ecc
    ports:
      - "13306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - ecc-backend

  mongodb:
    image: mongo:6.0
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ecc
    ports:
      - "12717:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - ecc-backend

  redis:
    image: redis:7.2
    restart: always
    ports:
      - "16379:6379"
    networks:
      - ecc-backend

volumes:
  mariadb_data:
  mongodb_data:

networks:
  ecc-backend:
