spring:
  ai:
    openai:
      base-url: ${SPRING_AI_OPENAI_BASE_URL}
      api-key: ${SPRING_AI_OPENAI_API_KEY}
      chat:
        options:
          max-tokens: ${SPRING_AI_OPENAI_CHAT_OPTIONS_MAX_TOKENS}
  
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
  
  jpa:
    properties:
      hibernate:
        format_sql: false
  
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
      password: ${SPRING_DATA_REDIS_PASSWORD}

jwt:
  secret: ${JWT_SECRET}

logging:
  file:
    name: /app/logs/application.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

server:
  port: 8080
  error:
    include-stacktrace: never  # 스택 트레이스 숨기기